GET http://localhost:3000/players/
Content-Type: application/json

###
GET http://localhost:3000/players/2/
Content-Type: application/json

###

PUT http://localhost:3000/players/2/
Content-Type: application/json

{
  "playerName": "Raju"
}

###

GET http://localhost:3000/matches/18/
Content-Type: application/json

###

GET http://localhost:3000/players/3/matches
Content-Type: application/json

###
GET http://localhost:3000/matches/3/players
Content-Type: application/json

###

GET http://localhost:3000/players/1/playerScores
Content-Type: application/json

###
